[CNXC-247] Re-running Current Analyses when Routing Back to Dashboard
darwinai/covidnet_ui pull request #32
Opened 2021-03-22 19:58 UTC by colinywu

### Problem Statement
Currently, after starting an analysis, COVID-Net re-runs the same analysis if the user goes to `Create Analysis` and routes back to `Dashboard` (before the previous analysis has finished)

### Implementation
Refactored code to create the analysis in CreateAnalysis, instead of Dashboard. Doing this, this resolves the issue of having mixed concerns and a bug of triggering current analyses to re-run when routing back to Dashboard repeatedly. Code now separates concerns and resolves the bug

2021-03-23 12:54 UTC, janakitti requested changes

2021-03-23 12:54 UTC, janakitti commented on src/components/CreateAnalysis/CreateAnalysisWrapper.tsx
> +       });
```suggestion
   // Processing the images
   CreateAnalysisService.analyzeImages(imagesSelected, models.xrayModel, models.ctModel) // Passing selected models to Chris_Integration for image analysis
   .then((notifications) => {
     dispatch({
       type: StagingDcmImagesTypes.UpdateStaging,
       payload: { imgs: [] }
     })
     dispatch({
       type: AnalysisTypes.Update_are_new_imgs_available,
       payload: { isAvailable: true }
     });
     dispatch({
       type: NotificationActionTypes.SEND,
       payload: { notifications }
     })
   });
```

2021-03-23 12:54 UTC, janakitti commented on src/pages/CreateAnalysisPage/CreateAnalysisPage.tsx
> +  const { state: {dcmImages} } = React.useContext(AppContext);
```suggestion
  const { state: { dcmImages } } = React.useContext(AppContext);
```

2021-03-23 12:54 UTC, janakitti commented on src/pages/Dashboard/Dashboard.tsx
> +  document.title = "Analysis - COVID-Net UI";
Setting the document title like this works, however I think the common practice is to wrap this in a `useEffect` with an empty dependency array.

2021-03-24 04:25 UTC, boris-nguyen commented on src/components/CreateAnalysis/CreateAnalysisWrapper.tsx
> +         })
```suggestion
         });
```

2021-03-24 04:25 UTC, boris-nguyen commented on src/components/CreateAnalysis/CreateAnalysisWrapper.tsx
> +         })
```suggestion
         });
```

2021-03-24 04:38 UTC, boris-nguyen reviewed
Please, fix the indentation and add missing semicolons.

2021-03-24 15:50 UTC, janakitti requested changes
Just 2 comments on adding semicolons and using double quotes for imports. After adding these, we should be good to go :+1:

2021-03-24 15:50 UTC, janakitti commented on src/pages/Dashboard/Dashboard.tsx
> +  }, [])
```suggestion
  }, []);
```

2021-03-24 15:50 UTC, janakitti commented on src/components/CreateAnalysis/CreateAnalysisWrapper.tsx
>  import { Drawer, DrawerActions, DrawerCloseButton, DrawerContent, DrawerContentBody, DrawerHead, DrawerPanelContent, Modal } from '@patternfly/react-core';
Change the imports so they use double quotes

2021-03-24 18:25 UTC, janakitti approved these changes
Great work, @colinywu!

2021-03-24 19:57 UTC, boris-nguyen approved these changes
Great work @colinywu!
Great to see Separation of Concerns rule being applied!

2021-03-24 21:04 UTC, merged