[CNXC-249] Patient MRN not displaying after search/re-routing
darwinai/covidnet_ui pull request #33
Opened 2021-03-22 20:08 UTC by colinywu

### Problem Statement
Currently, the patient MRN box is empty after performing a search, and also after routing back to the Create Analysis page.

### Implementation
Added createAnalysis store into CreateAnalysisDetail useEffect's dependency to now update and display the current patient MRN correctly, and also keep/store the value when re-routing back to the Create Analysis page during the same session. The value now stays in sync with Create Analysis page patient content.

2021-03-24 15:58 UTC, janakitti requested changes
Just a minor code formatting change.

2021-03-24 15:58 UTC, janakitti commented on src/components/PatientLookup.tsx
> +  const { state: {createAnalysis: {patientID}}, dispatch } = useContext(AppContext);
```suggestion
  const { state: { createAnalysis: { patientID } }, dispatch } = useContext(AppContext);
```

2021-03-30 13:22 UTC, janakitti commented on src/components/PatientLookup.tsx
> +  const { state: {createAnalysis: { patientID }}, dispatch } = useContext(AppContext);
```suggestion
  const { state: { createAnalysis: { patientID }}, dispatch } = useContext(AppContext);
```

2021-04-07 04:30 UTC, boris-nguyen approved these changes
Good job @colinywu !

2021-04-07 20:12 UTC, janakitti approved these changes
Looks great!

2021-04-07 20:12 UTC, merged