[CNXC-291] Analysis Created Pluralization
darwinai/covidnet_ui pull request #38
Opened 2021-04-07 20:50 UTC by colinywu

### Bug
When an analysis is ran 1 day ago, in the Past Analysis Table under the 'Analysis Created' column it says '1 days ago'

### Expected Behaviour
The value of the cell should be '1 day ago'

### Implementation
Added checking if the elapsed time since the analysis is greater than 1 day, and assigned string accordingly

2021-04-08 04:21 UTC, boris-nguyen requested changes
I would suggest using `moment.js` to get the relative time.

Firstly, we are already using `moment.js` in other places to format dates, so using moment for all time formatting would keep it consistent. Secondly, relative time in moment supports more relative date ranges such as "years ago"; in our implementation it would look like "132 weeks ago" as an example. Thirdly, using moment would help us avoid bugs and edge cases that were not considered during development of `modifyDatetime`. Lastly, we won't be reinventing a wheel.

@janakitti @colinywu let me know what you think about replacing `modifyDatetime()` logic with  `moment(<timestamp>).fromNow()`.

If we decide to leave the original logic, then I would highly suggest adding "year(s) ago" relative time.

2021-04-08 12:51 UTC, janakitti commented
> I would suggest using `moment.js` to get the relative time.
> 
> Firstly, we are already using `moment.js` in other places to format dates, so using moment for all time formatting would keep it consistent. Secondly, relative time in moment supports more relative date ranges such as "years ago"; in our implementation it would look like "132 weeks ago" as an example. Thirdly, using moment would help us avoid bugs and edge cases that were not considered during development of `modifyDatetime`. Lastly, we won't be reinventing a wheel.
> 
> @janakitti @colinywu let me know what you think about replacing `modifyDatetime()` logic with `moment(<timestamp>).fromNow()`.
> 
> If we decide to leave the original logic, then I would highly suggest adding "year(s) ago" relative time.

I agree that we should be using a library to handle this formatting. However. Moment.js is now considered a legacy project and they don't advise using it in new projects (and it's apparently also pretty bulky). COVID-Net currently only uses it in a few places. Would it be a good idea now to switch to another library (like Luxon)?

2021-04-08 13:15 UTC, boris-nguyen commented
> > I would suggest using `moment.js` to get the relative time.
> > Firstly, we are already using `moment.js` in other places to format dates, so using moment for all time formatting would keep it consistent. Secondly, relative time in moment supports more relative date ranges such as "years ago"; in our implementation it would look like "132 weeks ago" as an example. Thirdly, using moment would help us avoid bugs and edge cases that were not considered during development of `modifyDatetime`. Lastly, we won't be reinventing a wheel.
> > @janakitti @colinywu let me know what you think about replacing `modifyDatetime()` logic with `moment(<timestamp>).fromNow()`.
> > If we decide to leave the original logic, then I would highly suggest adding "year(s) ago" relative time.
> 
> @boris-nguyen @colinywu I agree that we should be using a library to handle this formatting. However. Moment.js is now considered a legacy project and they don't advise using it in new projects (and it's apparently also pretty bulky). COVID-Net currently only uses it in a few places. Would it be a good idea now to switch to another library (like Luxon)?

Nice catch @janakitti, didn't realize it became a legacy project a couple of months ago. Seems like Luxon is indeed the way to go.
https://momentjs.com/docs/#/-project-status/
https://terodox.tech/migrating-away-from-momentjs-part1/

Here's what I'm thinking:
1) Do a quick research about what is the best option for migrating away from moment.js
2) Estimate how much effort it would require to migrate away from moment.js
3) If it requires a lot of effort, create a separate Jira ticket to tackle the migration and in meantime just add "years ago" handling. If it does not require a lot of effort, then migrate away from moment.js.

@janakitti @colinywu Let me know what is your opinion about this.

2021-04-19 15:59 UTC, janakitti approved these changes
Great work, @colinywu!

2021-04-20 00:16 UTC, boris-nguyen commented on src/shared/utils.tsx
> +  return DateTime.fromISO(dateStr).toFormat('yyyy MM dd');
```suggestion
  return DateTime.fromISO(dateStr).toFormat("yyyy MM dd");
```

2021-04-20 00:17 UTC, boris-nguyen commented on src/shared/utils.tsx
> +  return oldDay.split('.')[0];
```suggestion
  return oldDay.split(".")[0];
```

2021-04-20 00:17 UTC, boris-nguyen commented on src/shared/utils.tsx
> +  return Math.trunc(-DateTime.fromISO(patientDOB).diffNow('years').years);
```suggestion
  return Math.trunc(-DateTime.fromISO(patientDOB).diffNow("years").years);
```

2021-04-20 00:18 UTC, boris-nguyen commented on src/shared/utils.tsx
> +  return (DateTime.fromISO(oldDay).toRelativeCalendar() || "").split(' ').map((date: string) => date.charAt(0).toUpperCase() + date.slice(1)).join(' ');
```suggestion
  return (DateTime.fromISO(oldDay).toRelativeCalendar() || "").split(" ").map((date: string) => date.charAt(0).toUpperCase() + date.slice(1)).join(" ");
```

2021-04-20 00:26 UTC, boris-nguyen approved these changes
Good work @colinywu

2021-04-21 21:44 UTC, merged