[CNXC-344] Highlighting Newly Finished Study Analyses Rows on the Past Analysis Table
darwinai/covidnet_ui pull request #75
Opened 2021-05-19 22:26 UTC by mslwang

I decided to make it so that showing that the task is finished would be based on whether at least one of the feeds (not necessarily all of them) in that row showed up as finished instead of using time stamps. Feeds are unique to their rows, so I thought this would be better desired behaviour, although the tradeoff is needing another more global (component level) variable tying into that function.

2021-05-25 17:28 UTC, micklynch commented on src/components/pastAnalysis/PastAnalysisTable.tsx
> +  const finishedFeedsRef = useRef<Set<number>>(new Set());
Can we revert back to using array of strings rather than `Set` so that all browsers are compatible.

2021-05-25 17:35 UTC, micklynch requested changes
Let's go through this again and perhaps see if we can explain what's happening.

2021-05-25 20:54 UTC, mslwang commented
> Let's go through this again and perhaps see if we can explain what's happening.

Old implementation: 
during the interval test, it checks for if the processing feeds are finished. 
Before the dispatch, the table has the same state where the feeds that just finished processing haven’t had their state reflected, meaning they’re still marked as processing in the table. 
The timestamps of the studies that don’t have jobs running are put into the newRowsRef ref object. When we update the table ui, each row is passed through a wrapper function. This wrapper function checks if that timestamp is in the newRowsRef if it’s done analyzing (which will be reflected after the dispatch), so if it’s not, we will highlight to show that’s it’s recently finished
One caveat is that the old implementation's issue was that the time wasn’t being reflected by number within the same day (ie. the timestamp is all "Today" instead of the time in hours, minutes, and seconds as desired), which we changed in another commit and which is why it’s not working in the old implementation

Whenever the rows collapse or expand, the wrapper is ran through the whole page, meaning that if the newRowsRef page is the same, it will cause the highlight to come up again

2021-06-15 18:30 UTC, mslwang commented
Updated PR #84

2021-06-15 18:30 UTC, closed without merging